# Generated by Django 4.0.4 on 2024-06-28 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0003_alter_vote_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='previous_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='block',
            name='timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='block',
            name='vote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='election.vote'),
        ),
    ]
