# Generated by Django 4.0.4 on 2024-06-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0004_alter_block_previous_hash_alter_block_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='images',
            field=models.ImageField(default='profile_picture/download_EPBN0x6.jpg', upload_to='profile_picture'),
        ),
    ]
